/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Arrays;

public class NQueensTest {

    // these are inadequate tests; they force a particular answer when there could
    // be more than one answer and it is undetermined which answer should be provided.

    // a better test would be to ensure there is an answer, and then some code
    // to check the answer.


    @Test public void test5() {
	int n = 5;
	NQueens nqueens = new NQueens(n);
	nqueens.placeRow(0);
	int[] expected = {-1, -1, -1, -1, -1};
	assertArrayEquals(expected, nqueens.board);
	// System.out.println(Arrays.toString(nqueens.board));
    }
    @Test public void test8() {
	int n = 8;
	NQueens nqueens = new NQueens(n);
	nqueens.placeRow(0);
	int[] expected = {2, 4, 7, 3, 0, 6, 1, 5};
	assertArrayEquals(expected, nqueens.board);
    }


}
